/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'

// https://github.com/wrongakram/React-Three-Minecraft-Chest/blob/master/src/components/Three/chest.js

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/music-box.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.3, 0.3, 0.3]}>
        <primitive object={nodes.Bone} />
        <primitive object={nodes.Bone001} />
        <skinnedMesh
          material={materials.DefaultMaterial}
          geometry={nodes['figurine-lo'].geometry}
          skeleton={nodes['figurine-lo'].skeleton}
        />
        <skinnedMesh
          material={materials.DefaultMaterial}
          geometry={nodes['lid-lo001'].geometry}
          skeleton={nodes['lid-lo001'].skeleton}
        />
      </group>
      <mesh material={materials.DefaultMaterial} geometry={nodes['box-lo'].geometry} />
    </group>
  )
}

useGLTF.preload('/music-box.glb')
